name: AderlyonTime
main: com.nktfh100.AderlyonTime.main.AderlyonTime
author: nktfh100
version: 1.0
api-version: 1.16
softdepend: [PlaceholderAPI]

commands:
   calendar:
      description: Open the calendar GUI